language: php

php:
	- 5.4
	- 5.5
	- 5.6

env:
  global:
	secure: LcmdRBX5bX8BbpHewAlUwBCRAzCkUvS+XdvY5Bjlbg2NdbAsQ1nPJfGVVfP2wb/vKOeU++6eZASi6X0MWlm1mdCp/6/nu5jSnFrkP/rokddpsictSL2GyM/C9bp45MZpshy6DqY8zoEfKtu9ZvHtVccdErVRrVlOr3ebcfB2uiw=

before_scripts:
        - git config --global user.email "travis@travis-ci.org"
	- git config --global user.name "Travis"

scripts:
        wget https://gist.githubusercontent.com/uiii/1fc5373c6f58ba29fb33/raw/40a8bf499e15910652c3f33aa9a0e413154f4b71/generate-api.sh && sh generate-api.sh

